import os

TEMPLATE_CLINGO_FILE_BOUNDARIES = os.path.join("clingo", "template")
REPLACE_TOKEN_IN_CLINGO_TEMPLATE = "% INSERT TEXTURE CONSTRAINTS HERE"
REPLACE_TOKEN_BOUNDARY_CONSTRAINT = "% INSERT CONSTRAINT BOUNDARY MATCH HERE"
REPLACE_TOKEN_IN_CLINGO_TEMPLATE_FOR_ADDITIONAL_CONSTRAINTS = "% INSERT ADDITIONAL HARD CONSTRAINTS HERE"
CLINGO_FILE = os.path.join("clingo", "clingo.lp")
CLINGO_OUTPUT = os.path.join("clingo", "clingo-output.txt")
SATISFIABLE_TOKEN = "SATISFIABLE"
FILLED_SPACE_TILE = "filled_space"